name: billboard
description: Dart interop for billboard.js charts library
version: 0.0.1
homepage: https://github.com/leftyio/billboard.dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0