name: billboard
description: Dart interop for billboard.js charts library
version: 0.2.0
homepage: https://github.com/leftyio/billboard.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.4
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0